# Generated by Django 4.1.3 on 2022-11-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='likes',
            new_name='liked',
        ),
    ]
