# Generated by Django 4.1.3 on 2022-11-16 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_album_year_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year_released',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1700)]),
        ),
    ]
