# Generated by Django 4.1.3 on 2022-11-16 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_alter_album_year_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year_released',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='jams.playlist'),
        ),
    ]
