# Generated by Django 4.1.3 on 2022-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0005_alter_album_year_released_alter_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, default=None, to='jams.playlist'),
        ),
    ]
