# Generated by Django 4.1.3 on 2022-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0007_alter_album_artist_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
